language: node_js
sudo: required
services:
  - docker
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
jobs:
  include:
  - stage: test
    install:
      - npm install
    script:
       - npm test
  - stage: release
    script:
    - npm run release
stages:
- test
- name: release
  if: branch = master AND type = push AND fork = false
